# lib/acceptance-adr0143-init-mcp.sh — ADR-0143 AC#5 automated MCP-config check
#
# Replaces the manual smoke "npx @sparkleideas/ruflo init generates a
# .mcp.json with args [\"-y\", \"@sparkleideas/ruflo\", \"mcp\", \"start\"]".
# Per project policy, everything via build/deploy scripts — never manual.
#
# Verifies ADR-0143 §B2 contract end-to-end:
#   1. Fresh tmp dir, install @sparkleideas/ruflo from Verdaccio
#   2. Run `ruflo init` (via the wrapper) in non-interactive mode
#   3. Read the generated .mcp.json (or .claude/.mcp.json)
#   4. Assert mcpServers entry references @sparkleideas/ruflo (not @sparkleideas/cli),
#      OR uses the path-1 form (command: <local-bin>, args: [mcp, start]).
#      The acceptance check for ADR-0117 already accepts both — same contract here.

# shellcheck disable=SC2034  # _CHECK_PASSED set as a side-effect

check_adr0143_init_mcp_config() {
  local start_ns end_ns
  start_ns=$(_ns)
  _CHECK_PASSED="false"

  local init_tmp
  init_tmp=$(mktemp -d /tmp/ruflo-adr0143-init-mcp-XXXXX)
  # shellcheck disable=SC2064
  trap "rm -rf '$init_tmp'" RETURN

  # Install wrapper into tmp dir
  (cd "$init_tmp" \
    && echo '{"name":"adr0143-init-test","version":"1.0.0","private":true}' > package.json \
    && echo "registry=${REGISTRY}" > .npmrc \
    && npm install @sparkleideas/ruflo --registry "$REGISTRY" \
       --cache "$init_tmp/.npm-cache" \
       --no-audit --no-fund --prefer-offline 2>&1 > "$init_tmp/install.log") || {
    _CHECK_OUTPUT="ADR-0143-init: npm install failed (see $init_tmp/install.log)"
    end_ns=$(_ns); _EXIT=1; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"; return
  }

  local wrapper_bin="${init_tmp}/node_modules/.bin/ruflo"
  if [[ ! -x "$wrapper_bin" ]]; then
    _CHECK_OUTPUT="ADR-0143-init: wrapper bin missing at ${wrapper_bin}"
    end_ns=$(_ns); _EXIT=1; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"; return
  fi

  # Run init in non-interactive mode. --yes / --force suppress prompts.
  # We need a project-root marker for findProjectRoot to anchor to init_tmp.
  : > "${init_tmp}/.ruflo-project"
  local init_log="${init_tmp}/init.log"
  (cd "$init_tmp" && NPM_CONFIG_REGISTRY="$REGISTRY" \
    _timeout 60 "$wrapper_bin" init --yes --force > "$init_log" 2>&1) || true

  # The init writes .mcp.json at project root (or .claude/.mcp.json depending
  # on init template). Look in both common locations.
  local mcp_file=""
  for candidate in "${init_tmp}/.mcp.json" "${init_tmp}/.claude/.mcp.json" "${init_tmp}/.claude-flow/.mcp.json"; do
    if [[ -f "$candidate" ]]; then
      mcp_file="$candidate"
      break
    fi
  done

  if [[ -z "$mcp_file" ]]; then
    _CHECK_OUTPUT="ADR-0143-init: no .mcp.json generated by 'ruflo init'. Init log first 15:
$(head -15 "$init_log" 2>/dev/null)"
    end_ns=$(_ns); _EXIT=1; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"; return
  fi

  # Parse + validate. Same dual-path acceptance as ADR-0117 AC#1:
  #   path 1: command=<local-bin-path>, args=['mcp','start']
  #   path 2: command='npx', args=[..., '@sparkleideas/ruflo' OR '@sparkleideas/cli', ...]
  # (the ADR-0117 fix established this dual-path contract; mirror here)
  local result
  result=$(node -e "
    const fs = require('fs');
    const j = JSON.parse(fs.readFileSync('$mcp_file','utf8'));
    const ms = j.mcpServers || {};
    const ruflo = ms.ruflo || ms['claude-flow'] || ms.cli;
    if (!ruflo) { console.log('NO_MCP_SERVER_KEY:' + JSON.stringify(Object.keys(ms))); process.exit(0); }
    const args = (ruflo.args || []).join(' ');
    const cmd = ruflo.command || '';
    const path1 = /\bruflo\$/.test(cmd) && args === 'mcp start';
    const path2 = args.includes('@sparkleideas/ruflo');
    const cliBypass = args.includes('@sparkleideas/cli');
    if (path2) { console.log('OK_PATH2_RUFLO:' + args); process.exit(0); }
    if (path1) { console.log('OK_PATH1_LOCAL_BIN:cmd=' + cmd + ' args=' + args); process.exit(0); }
    if (cliBypass) { console.log('VIOLATION_CLI_BYPASS:' + args + ' (ADR-0143 B2 expected ruflo, got cli)'); process.exit(0); }
    console.log('UNRECOGNIZED:cmd=' + cmd + ' args=' + args);
  " 2>&1)

  if [[ "$result" == OK_PATH2_RUFLO:* || "$result" == OK_PATH1_LOCAL_BIN:* ]]; then
    _CHECK_PASSED="true"
    _CHECK_OUTPUT="ADR-0143-init PASS: init-generated .mcp.json registers ruflo via wrapper-canonical path (${result})"
    end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"; return
  fi

  _CHECK_OUTPUT="ADR-0143-init: init-generated .mcp.json doesn't satisfy B2 contract (${result}). File: ${mcp_file}"
  end_ns=$(_ns); _EXIT=1; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
}
