#!/usr/bin/env bash
# lib/acceptance-adr0098-checks.sh — ADR-0098 acceptance checks
#
# Swarm-init sprawl fix:
#   (a) Generator CLAUDE.md no longer advertises reflex swarm_init
#   (b) MCP swarm_init handler reuses matching running swarms (config-fingerprint dedupe)
#   (c) `swarm init --new` bypasses dedupe
#
# Requires: _cli_cmd, _run_and_kill, _e2e_isolate from acceptance-harness.sh
# Caller MUST set: REGISTRY, TEMP_DIR (or E2E_DIR)

set +u 2>/dev/null || true

# ════════════════════════════════════════════════════════════════════
# ADR-0098-A: generated CLAUDE.md does NOT contain pre-fix reflex-init strings
# ════════════════════════════════════════════════════════════════════
check_adr0098_a_generator_no_reflex_swarm() {
  _CHECK_PASSED="false"
  _CHECK_OUTPUT=""

  # Use a truly fresh dir (NOT `_e2e_isolate`) — the iso helper seeds
  # `.claude-flow/config.json` from E2E_DIR, which causes `init --full` to
  # short-circuit ("RuFlo appears to be already initialized") and skip
  # CLAUDE.md generation. We need the generator to run end-to-end on a cold
  # project so we can inspect its exact output. Pattern mirrors P5's
  # check_p5_flag_* helpers in acceptance-init-generated-checks.sh.
  if [[ -z "$CLI_BIN" ]]; then
    _CHECK_OUTPUT="ADR-0098-A: CLI_BIN not set (caller must export it)"
    return
  fi
  local iso; iso=$(mktemp -d /tmp/ruflo-adr0098a-XXXXX)
  # Symlink node_modules so the CLI can resolve its own deps without reinstalling.
  if [[ -n "$TEMP_DIR" && -d "$TEMP_DIR/node_modules" ]]; then
    ln -sf "$TEMP_DIR/node_modules" "$iso/node_modules"
  fi

  # Init a fresh project — CLAUDE.md is generated at init time.
  local init_out
  init_out=$(cd "$iso" && NPM_CONFIG_REGISTRY="$REGISTRY" timeout 60 "$CLI_BIN" init --full --quiet 2>&1) || true

  if [[ ! -f "$iso/CLAUDE.md" ]]; then
    _CHECK_OUTPUT="ADR-0098-A: CLAUDE.md not generated by init (init output: ${init_out:0:200})"
    rm -rf "$iso" 2>/dev/null; return
  fi

  local claudemd="$iso/CLAUDE.md"
  local hits=""

  # Pre-fix instruction fragments that MUST NOT appear in a post-fix generator.
  # Each of these was identified in ADR-0098 "Context §1" as a driver of
  # reflex swarm_init. If any appears, the generator regression-bit.
  #
  # Check 1: the old "Use CLI tools ... swarm init" bullet
  if grep -qF "CLI tools (via Bash) for coordination: swarm init" "$claudemd"; then
    hits="${hits}L72 (coordination bullet);"
  fi
  # Check 2: the pre-commit "ALWAYS use hierarchical topology" phrasing
  if grep -qF "ALWAYS use hierarchical topology for coding swarms" "$claudemd"; then
    hits="${hits}L79 (ALWAYS hierarchical);"
  fi
  # Check 3: the worked-example copy-bait line
  if grep -qF 'ruflo swarm init --topology hierarchical --max-agents 8 --strategy specialized' "$claudemd"; then
    hits="${hits}L87 (worked example);"
  fi
  # Check 4: the "Initialize a swarm | ruflo swarm init via Bash" table row
  if grep -qE 'Initialize a swarm.*ruflo swarm init.*via Bash' "$claudemd"; then
    hits="${hits}L128 (table row);"
  fi

  if [[ -n "$hits" ]]; then
    _CHECK_OUTPUT="ADR-0098-A: generator REGRESSED — pre-fix strings present in CLAUDE.md: ${hits}"
    rm -rf "$iso" 2>/dev/null; return
  fi

  # Positive assertion: the post-fix guardrail language IS present
  if ! grep -qF "DO NOT call" "$claudemd" || ! grep -qF "reflexively" "$claudemd"; then
    _CHECK_OUTPUT="ADR-0098-A: generator missing post-fix guardrail ('DO NOT call ... reflexively')"
    rm -rf "$iso" 2>/dev/null; return
  fi

  _CHECK_PASSED="true"
  _CHECK_OUTPUT="ADR-0098-A: generated CLAUDE.md free of reflex-init strings + has guardrail"
  rm -rf "$iso" 2>/dev/null
}

# ════════════════════════════════════════════════════════════════════
# ADR-0098-B: repeated `swarm init` with same config stays at 1 record
# ════════════════════════════════════════════════════════════════════
check_adr0098_b_swarm_init_dedupe() {
  _CHECK_PASSED="false"
  _CHECK_OUTPUT=""
  local cli; cli=$(_cli_cmd)
  local iso; iso=$(_e2e_isolate "adr0098-b")

  # First init
  _run_and_kill "cd '$iso' && NPM_CONFIG_REGISTRY='$REGISTRY' $cli init --full --quiet" "" 120

  # Three `swarm init` calls with the same default config
  _run_and_kill "cd '$iso' && NPM_CONFIG_REGISTRY='$REGISTRY' $cli swarm init" "" 30
  _run_and_kill "cd '$iso' && NPM_CONFIG_REGISTRY='$REGISTRY' $cli swarm init" "" 30
  local third_out; _run_and_kill "cd '$iso' && NPM_CONFIG_REGISTRY='$REGISTRY' $cli swarm init" "" 30
  third_out="$_RK_OUT"

  local state_file="$iso/.swarm/swarm-state.json"
  if [[ ! -f "$state_file" ]]; then
    _CHECK_OUTPUT="ADR-0098-B: .swarm/swarm-state.json not created by swarm init"
    rm -rf "$iso" 2>/dev/null; return
  fi

  local count
  count=$(python3 -c "import json; d=json.load(open('$state_file')); print(len(d.get('swarms',{})))" 2>/dev/null)
  count=${count:-0}

  if [[ "$count" != "1" ]]; then
    _CHECK_OUTPUT="ADR-0098-B: dedupe REGRESSED — 3 same-config inits produced $count records, expected 1. third-call output: ${third_out:0:200}"
    rm -rf "$iso" 2>/dev/null; return
  fi

  # Assert the CLI logged "Reusing" on the 2nd/3rd calls
  if ! echo "$third_out" | grep -qiE 'reusing|reused'; then
    _CHECK_OUTPUT="ADR-0098-B: record count correct (1) but CLI did not surface 'Reusing' message on repeat init: ${third_out:0:200}"
    rm -rf "$iso" 2>/dev/null; return
  fi

  _CHECK_PASSED="true"
  _CHECK_OUTPUT="ADR-0098-B: 3 same-config swarm init calls collapsed to 1 record + reuse surfaced"
  rm -rf "$iso" 2>/dev/null
}

# ════════════════════════════════════════════════════════════════════
# ADR-0098-C: `swarm init --new` bypasses dedupe
# ════════════════════════════════════════════════════════════════════
check_adr0098_c_swarm_init_new_flag() {
  _CHECK_PASSED="false"
  _CHECK_OUTPUT=""
  local cli; cli=$(_cli_cmd)
  local iso; iso=$(_e2e_isolate "adr0098-c")

  _run_and_kill "cd '$iso' && NPM_CONFIG_REGISTRY='$REGISTRY' $cli init --full --quiet" "" 120

  _run_and_kill "cd '$iso' && NPM_CONFIG_REGISTRY='$REGISTRY' $cli swarm init" "" 30
  _run_and_kill "cd '$iso' && NPM_CONFIG_REGISTRY='$REGISTRY' $cli swarm init --new --reason adr0098-acceptance" "" 30

  local state_file="$iso/.swarm/swarm-state.json"
  local count
  count=$(python3 -c "import json; d=json.load(open('$state_file')); print(len(d.get('swarms',{})))" 2>/dev/null)
  count=${count:-0}

  if [[ "$count" != "2" ]]; then
    _CHECK_OUTPUT="ADR-0098-C: --new flag FAILED to bypass dedupe: got $count records, expected 2"
    rm -rf "$iso" 2>/dev/null; return
  fi

  _CHECK_PASSED="true"
  _CHECK_OUTPUT="ADR-0098-C: --new flag correctly created a second swarm with same config"
  rm -rf "$iso" 2>/dev/null
}
