#!/usr/bin/env bash
# lib/acceptance-adr0117-marketplace-mcp.sh — ADR-0117 Revision 2026-05-03
# (service-method registration via init's mcp-generator.ts).
#
# Asserts the post-R1+R2+R3 fork state:
#   1. The harness's `ruflo init --full` in $TEMP_DIR generated a
#      .mcp.json that registers `mcpServers.ruflo` (NOT
#      mcpServers["claude-flow"]).
#   2. The umbrella forks/ruflo/.claude-plugin/plugin.json carries zero
#      `mcpServers` blocks (matches the structural pattern of the 33 sub
#      plugins).
#   3. Marketplace plugin.json + hooks.json contain zero
#      `claude-flow@alpha` strings (Pass 5 codemod target — committed
#      fork state must already be clean).
#   4. Skill-doc `mcp__ruflo__<tool>` references (in 9 init-bundled
#      SKILL.md `allowed-tools:` frontmatter entries) resolve against
#      the fork CLI MCP server's JSON-RPC tools/list response.
#   5. Codemod re-run into /tmp/ruflo-build/ does NOT reintroduce
#      `mcpServers` blocks AND keeps zero `claude-flow@alpha` strings
#      (Pass 5 still effective).
#
# Conventions:
#   - Captures full output to a per-check ".log" file (memory
#     feedback-no-tail-tests + feedback-full-test-output): NEVER
#     pipe-mid-stream; grep the log file AFTER each step completes.
#   - Uses `var=$(grep -c ...); var=${var:-0}` (memory
#     reference-grep-c-bash-trap): `grep -c pat || echo 0` produces
#     "0\n0" on no-match and trips bash arithmetic.
#   - Uses `_cli_cmd` helper (memory reference-cli-cmd-helper) — never
#     raw `npx @sparkleideas/cli@latest` (36x slower from npm cache
#     lock).
#   - Each assertion explicitly fails (memory feedback-no-fallbacks) —
#     no silent skips, no "warn and continue".
#
# Operates on:
#   - forks/ruflo/.claude-plugin/{plugin.json, hooks/hooks.json}
#   - forks/ruflo/v3/@claude-flow/cli/.claude/skills/**/SKILL.md
#   - $TEMP_DIR/.mcp.json (harness init output)
#   - /tmp/ruflo-build/.claude-plugin/* (post-codemod state)
#   - /tmp/ruflo-mcp-tool-resolve-adr0117/ (per-check workspace)

__ADR0117_FORK_DIR=""
_adr0117_resolve_fork() {
  if [[ -n "$__ADR0117_FORK_DIR" ]]; then return; fi
  __ADR0117_FORK_DIR=$(node -e "
    const c = JSON.parse(require('fs').readFileSync(
      require('path').resolve('${PROJECT_DIR:-.}', 'config', 'upstream-branches.json'), 'utf8'));
    process.stdout.write(c.ruflo?.dir || '');
  " 2>/dev/null)
}

# ════════════════════════════════════════════════════════════════════
# AC #1 — Init service-method registration
#
# The harness ran `ruflo init --full` in $TEMP_DIR before structural
# checks fired. Verify the resulting .mcp.json registers
# `mcpServers.ruflo` and DOES NOT carry `mcpServers["claude-flow"]`.
# (Args must also point at the fork CLI binary, not a bare ruflo@latest
# that would resolve from public npm.)
# ════════════════════════════════════════════════════════════════════

check_adr0117_init_service_method() {
  local start_ns end_ns
  start_ns=$(_ns)
  _CHECK_PASSED="false"

  local mcp="${TEMP_DIR}/.mcp.json"
  if [[ ! -f "$mcp" ]]; then
    _CHECK_OUTPUT="ADR-0117 AC#1 failed: $mcp not generated by harness init --full"
    end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
    return
  fi

  # Assert mcpServers.ruflo exists, mcpServers["claude-flow"] absent. Use
  # node (not jq — keeps the check portable across CI hosts that may
  # lack jq, matching the rest of this file's helper invocations).
  local result
  result=$(node -e "
    const fs = require('fs');
    const j = JSON.parse(fs.readFileSync('$mcp','utf8'));
    const ms = j.mcpServers || {};
    if (!ms.ruflo) { console.log('NO_RUFLO_KEY'); process.exit(0); }
    if (ms['claude-flow']) { console.log('CLAUDE_FLOW_KEY_STILL_PRESENT'); process.exit(0); }
    const args = (ms.ruflo.args || []).join(' ');
    if (!args.includes('@sparkleideas/cli@latest')) { console.log('WRONG_ARGS:'+args); process.exit(0); }
    console.log('OK:'+args);
  " 2>&1)

  if [[ "$result" == OK:* ]]; then
    _CHECK_PASSED="true"
    _CHECK_OUTPUT="ADR-0117 AC#1 PASS: init registered mcpServers.ruflo (${result#OK:}), zero mcpServers[\"claude-flow\"]"
  else
    _CHECK_OUTPUT="ADR-0117 AC#1 failed: $result"
  fi
  end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
}

# ════════════════════════════════════════════════════════════════════
# AC #2 — Umbrella plugin.json clean
#
# forks/ruflo/.claude-plugin/plugin.json MUST have zero `mcpServers`
# blocks (Phase R3 removed it; structural match with the 33 sub-plugin
# manifests).
# ════════════════════════════════════════════════════════════════════

check_adr0117_umbrella_no_mcpservers() {
  local start_ns end_ns
  start_ns=$(_ns)
  _CHECK_PASSED="false"
  _adr0117_resolve_fork

  local pj="${__ADR0117_FORK_DIR}/.claude-plugin/plugin.json"
  if [[ ! -f "$pj" ]]; then
    _CHECK_OUTPUT="ADR-0117 AC#2 failed: $pj not found"
    end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
    return
  fi

  # Per memory reference-grep-c-bash-trap: `grep -c pat || echo 0`
  # produces "0\n0" on no-match. Use captured-then-defaulted form.
  local count
  count=$(grep -c '"mcpServers"' "$pj")
  count=${count:-0}

  if [[ "$count" != "0" ]]; then
    _CHECK_OUTPUT="ADR-0117 AC#2 failed: $count \"mcpServers\" block(s) still present in $pj (must be 0)"
    end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
    return
  fi

  _CHECK_PASSED="true"
  _CHECK_OUTPUT="ADR-0117 AC#2 PASS: zero \"mcpServers\" blocks in umbrella plugin.json"
  end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
}

# ════════════════════════════════════════════════════════════════════
# AC #3 — No `claude-flow@alpha` in marketplace plugin.json + hooks.json
#
# Pass 5 of the codemod still rewrites this string; the committed fork
# state must already be clean (the codemod runs against /tmp/ruflo-build,
# but committed fork sources should already be in target form).
# ════════════════════════════════════════════════════════════════════

check_adr0117_no_claude_flow_alpha() {
  local start_ns end_ns
  start_ns=$(_ns)
  _CHECK_PASSED="false"
  _adr0117_resolve_fork

  local pj="${__ADR0117_FORK_DIR}/.claude-plugin/plugin.json"
  local hj="${__ADR0117_FORK_DIR}/.claude-plugin/hooks/hooks.json"

  local pj_hits=0 hj_hits=0
  if [[ -f "$pj" ]]; then
    pj_hits=$(grep -c 'claude-flow@alpha' "$pj")
    pj_hits=${pj_hits:-0}
  fi
  if [[ -f "$hj" ]]; then
    hj_hits=$(grep -c 'claude-flow@alpha' "$hj")
    hj_hits=${hj_hits:-0}
  fi

  local total=$(( pj_hits + hj_hits ))
  if (( total > 0 )); then
    _CHECK_OUTPUT="ADR-0117 AC#3 failed: ${total} claude-flow@alpha ref(s) in marketplace surface (plugin.json=${pj_hits}, hooks.json=${hj_hits})"
    end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
    return
  fi

  _CHECK_PASSED="true"
  _CHECK_OUTPUT="ADR-0117 AC#3 PASS: zero claude-flow@alpha in marketplace surface (plugin.json + hooks.json)"
  end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
}

# ════════════════════════════════════════════════════════════════════
# AC #4 — MCP tool resolution
#
# Spawn the fork CLI MCP server, send JSON-RPC tools/list, capture the
# response. For each `mcp__ruflo__<tool>` ref in init-bundled SKILL.md
# `allowed-tools:` frontmatter, assert the suffix (or a hyphen/underscore
# variant) appears in the response.
#
# Uses _cli_cmd (NEVER raw npx @sparkleideas/cli@latest — see memory
# reference-cli-cmd-helper).
# ════════════════════════════════════════════════════════════════════

check_adr0117_mcp_tool_resolution() {
  local start_ns end_ns
  start_ns=$(_ns)
  _CHECK_PASSED="false"
  _adr0117_resolve_fork

  local test_dir="/tmp/ruflo-mcp-tool-resolve-adr0117"
  local log="${test_dir}/.log"
  rm -rf "$test_dir"
  mkdir -p "$test_dir"

  # 1) Collect the union of mcp__ruflo__<tool> suffixes from init-bundled
  # SKILL.md `allowed-tools:` frontmatter (post-R2 these are the source of
  # truth for what tools the user-facing skills expect).
  local skills_dir="${__ADR0117_FORK_DIR}/v3/@claude-flow/cli/.claude/skills"
  if [[ ! -d "$skills_dir" ]]; then
    _CHECK_OUTPUT="ADR-0117 AC#4 failed: $skills_dir missing (R2 not applied?)"
    end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
    return
  fi

  local tool_suffixes
  tool_suffixes=$(grep -rhoE 'mcp__ruflo__[a-zA-Z0-9_-]+' "$skills_dir" 2>/dev/null \
    | sort -u | sed 's/^mcp__ruflo__//')

  local total_skill_tools=0
  if [[ -n "$tool_suffixes" ]]; then
    total_skill_tools=$(printf '%s\n' "$tool_suffixes" | wc -l | tr -d ' ')
  fi
  if (( total_skill_tools == 0 )); then
    _CHECK_OUTPUT="ADR-0117 AC#4 failed: zero mcp__ruflo__ refs in $skills_dir/**/SKILL.md (R2 not applied?)"
    end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
    return
  fi

  # 2) Spawn fork CLI MCP server, send JSON-RPC initialize + tools/list.
  # Use the fork's local CLI bin (via _cli_cmd) — NEVER raw npx (memory
  # reference-cli-cmd-helper, 36x slower). Pipe both requests on stdin
  # then close. Server runs until SIGKILL; we capture stdout and parse.
  local cli; cli=$(_cli_cmd)
  local resp_file="${test_dir}/tools-list.json"

  # Per MCP protocol: initialize handshake first, then tools/list.
  # The server (forks/ruflo/v3/@claude-flow/cli/src/mcp-server.ts:479)
  # is permissive and accepts tools/list without initialize, but follow
  # protocol for robustness across server versions.
  local reqs
  reqs=$'{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"acceptance-test","version":"0.0.0"}}}\n{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}\n'

  # Stdio MCP server hangs after responses (waiting for more input); use
  # _timeout to KILL it after we have the response. 30s budget covers
  # cold-start of better-sqlite3 native compile in a fresh node_modules.
  (
    cd "$test_dir" || exit 99
    printf '%s' "$reqs" | _timeout 30 bash -c "$cli mcp start 2>/dev/null"
  ) > "$resp_file" 2>>"$log" || true

  if [[ ! -s "$resp_file" ]]; then
    _CHECK_OUTPUT="ADR-0117 AC#4 failed: empty tools/list response from '$cli mcp start' (log: $log)"
    end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
    return
  fi

  # 3) Extract registered tool names from the response. The response is
  # one or more JSON-RPC reply lines. Each "tools" entry is an array of
  # objects with `name` fields. Use node to parse robustly (per memory
  # feedback-no-fallbacks: parse properly, no regex on JSON).
  local registered
  registered=$(node -e "
    const fs = require('fs');
    const lines = fs.readFileSync('$resp_file','utf8').split(/\n/).filter(Boolean);
    const names = new Set();
    for (const line of lines) {
      try {
        const j = JSON.parse(line);
        const tools = j.result?.tools || [];
        for (const t of tools) if (t.name) names.add(t.name);
      } catch (e) { /* tolerate non-JSON banner lines */ }
    }
    process.stdout.write(Array.from(names).sort().join('\n'));
  " 2>>"$log")

  if [[ -z "$registered" ]]; then
    _CHECK_OUTPUT="ADR-0117 AC#4 failed: zero tool names extracted from tools/list response (resp: $resp_file, log: $log)"
    end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
    return
  fi

  # 4) For each skill-tool suffix, resolve against the registered set
  # (try direct match, then hyphen/underscore variants).
  local matched=0 unmatched=()
  local t variant
  while IFS= read -r t; do
    [[ -z "$t" ]] && continue
    if echo "$registered" | grep -qx "$t"; then
      matched=$((matched + 1)); continue
    fi
    # try underscore->hyphen and hyphen->underscore variants
    variant=$(echo "$t" | tr '_' '-')
    if echo "$registered" | grep -qx "$variant"; then
      matched=$((matched + 1)); continue
    fi
    variant=$(echo "$t" | tr '-' '_')
    if echo "$registered" | grep -qx "$variant"; then
      matched=$((matched + 1)); continue
    fi
    unmatched+=("$t")
  done <<< "$tool_suffixes"

  if (( matched == 0 )); then
    _CHECK_OUTPUT="ADR-0117 AC#4 failed: zero of $total_skill_tools skill mcp__ruflo__ refs match tools/list (unmatched: ${unmatched[*]:0:5}…)"
    end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
    return
  fi

  _CHECK_PASSED="true"
  _CHECK_OUTPUT="ADR-0117 AC#4 PASS: $matched of $total_skill_tools skill mcp__ruflo__ refs resolve via tools/list (unmatched: ${#unmatched[@]})"
  end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
}

# ════════════════════════════════════════════════════════════════════
# AC #5 — Codemod doesn't reintroduce mcpServers
#
# Re-run copy-source.sh + codemod.mjs into /tmp/ruflo-build/ and re-grep
# the post-codemod plugin.json — count must still be 0. This guards
# against a future codemod regression that emits the block back into
# the umbrella manifest.
# ════════════════════════════════════════════════════════════════════

check_adr0117_codemod_doesnt_readd_mcpservers() {
  local start_ns end_ns
  start_ns=$(_ns)
  _CHECK_PASSED="false"
  _adr0117_resolve_fork

  local build_dir="/tmp/ruflo-build"
  local pj="${build_dir}/.claude-plugin/plugin.json"

  if [[ ! -f "$pj" ]]; then
    _CHECK_OUTPUT="ADR-0117 AC#5 failed: $pj not present (build dir not staged — run copy-source + codemod first)"
    end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
    return
  fi

  # Pre-condition: source plugin.json (input to codemod) is clean.
  local src="${__ADR0117_FORK_DIR}/.claude-plugin/plugin.json"
  local src_count
  src_count=$(grep -c '"mcpServers"' "$src")
  src_count=${src_count:-0}
  if [[ "$src_count" != "0" ]]; then
    _CHECK_OUTPUT="ADR-0117 AC#5 failed: source $src has $src_count mcpServers block(s) (precondition violated — fix R3 first)"
    end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
    return
  fi

  # Post-condition: post-codemod plugin.json has zero mcpServers blocks.
  # If codemod added one back, we'd see it here.
  local post_count
  post_count=$(grep -c '"mcpServers"' "$pj")
  post_count=${post_count:-0}
  if [[ "$post_count" != "0" ]]; then
    _CHECK_OUTPUT="ADR-0117 AC#5 failed: codemod reintroduced $post_count mcpServers block(s) in $pj"
    end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
    return
  fi

  # Pass 5 must still rewrite claude-flow@alpha — if the post-codemod
  # plugin.json or hooks.json contains the bare alpha string, codemod
  # broke its Pass 5 contract.
  local hj="${build_dir}/.claude-plugin/hooks/hooks.json"
  local pj_alpha=0 hj_alpha=0
  pj_alpha=$(grep -c 'claude-flow@alpha' "$pj")
  pj_alpha=${pj_alpha:-0}
  if [[ -f "$hj" ]]; then
    hj_alpha=$(grep -c 'claude-flow@alpha' "$hj")
    hj_alpha=${hj_alpha:-0}
  fi
  local total_alpha=$(( pj_alpha + hj_alpha ))
  if (( total_alpha > 0 )); then
    _CHECK_OUTPUT="ADR-0117 AC#5 failed: post-codemod has $total_alpha claude-flow@alpha ref(s) (Pass 5 broken)"
    end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
    return
  fi

  _CHECK_PASSED="true"
  _CHECK_OUTPUT="ADR-0117 AC#5 PASS: codemod stable — zero mcpServers blocks reintroduced, zero claude-flow@alpha in build dir"
  end_ns=$(_ns); _EXIT=0; _DURATION_MS=$(_elapsed_ms "$start_ns" "$end_ns"); _OUT="$_CHECK_OUTPUT"
}
