storage: ./storage
max_body_size: 100mb
server:
  keepAliveTimeout: 60
uplinks: {}
packages:
  '@sparkleideas/*':
    access: $all
    publish: $all
  'ruflo':
    access: $all
    publish: $all
  '**':
    access: $all
    publish: $all
auth:
  htpasswd:
    file: ./htpasswd
    max_users: 10
log:
  type: file
  path: ./verdaccio.log
  level: warn
